Documentation:
  Enabled: false
Rails:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: false
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/support/model_macros.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'
    - 'app/controllers/users/unlocks_controller.rb'
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/controllers/users/passwords_controller.rb'
    - 'app/controllers/users/confirmations_controller.rb'
    - 'app/helpers/carousel_helper.rb'
