# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c978ee16295e8b5053533a108a175fd14102e2c63f83768c094840bad1a4f30439b2b5277049ac56303ed95cfee4c75e092cb75bd78f38063828551d5e29e5c

test:
  secret_key_base: 185c0c67576869b9f033f662d5bccc03645d6696c878dababd997e74f0493e85dc50dbc520ed6310407c02375addb0f25912b1fdd50e1ed7a053f08093f8424a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
